version: 2

jobs:
#  macos:
#    macos:
#      xcode: "10.1.0"
#    steps:
#      - checkout
#      - run: swift build
#      - run: swift test

  linux:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux-release:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - checkout
      - run: swift build -c release


workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
      - macos
